/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Contact = IDL.Record({
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'addContact' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteContact' : IDL.Func([IDL.Text], [], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getContactByName' : IDL.Func([IDL.Text], [Contact], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Contact = IDL.Record({ 'name' : IDL.Text, 'phoneNumber' : IDL.Text });
  
  return IDL.Service({
    'addContact' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteContact' : IDL.Func([IDL.Text], [], []),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getContactByName' : IDL.Func([IDL.Text], [Contact], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };